

use failure;
use compiler::run;

fn main() -> Result<(), failure::Error>{
    run()
}
